name: Build and Publish

on:
  push:
    branches: [halfmatthalfcat]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Configure Git
        run: |
          git config --local user.email "mjo2089@gmail.com"
          git config --local user.name "Matt Oliver"

      - name: Bump prerelease version
        run: |
          npm version prerelease --preid next
          git push --follow-tags

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
